CREATE DATABASE IF NOT EXISTS trading;
CREATE DATABASE IF NOT EXISTS auth;

CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'wqdsdsf123!';
GRANT ALL PRIVILEGES ON trading.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON auth.* TO 'user'@'%';

FLUSH PRIVILEGES;
